// src/content/curriculum/modules.ts
export interface Module {
  id: string;
  cycle: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  order: number;
  title: string;
  description: string | null;
  anchorVerse: string;
  anchorReference: string;
  method: string;
  xp: number;
  exercises: number;
}

export const MODULES: Module[] = [
  // ─── CICLO I ───────────────────────────────────────
  { id: 'C1-M00', cycle: 1, order: 0,  title: 'Bem-vindos ao Grego Bíblico',             description: 'Introdução do Ciclo I', anchorVerse: 'Ἐν ἀρχῇ ἦν ὁ λόγος', anchorReference: 'João 1:1', method: 'Áudio guiado',                               xp: 0,   exercises: 0 },
  { id: 'C1-M01', cycle: 1, order: 1,  title: 'Vogais Base: Α, Ε, Ι',                  description: null, anchorVerse: 'ἠγάπησεν',           anchorReference: 'João 3:16',    method: 'Flashcard + Canvas 2D + Áudio',                xp: 60,  exercises: 11 },
  { id: 'C1-M02', cycle: 1, order: 2,  title: 'Vogais: Ο, Υ, Ω',                       description: null, anchorVerse: 'χωρὶς αὐτοῦ',        anchorReference: 'João 1:3',     method: 'Flashcard + Canvas 2D + Distinção de sons',     xp: 60,  exercises: 11 },
  { id: 'C1-M03', cycle: 1, order: 3,  title: 'Consoantes Η, Ν, Τ',                    description: null, anchorVerse: 'Ἐν ἀρχῇ ἦν',         anchorReference: 'João 1:1',     method: 'Flashcard + Canvas 2D + Sílabas',              xp: 65,  exercises: 11 },
  { id: 'C1-M04', cycle: 1, order: 4,  title: 'Consoantes Σ, Κ, Λ',                    description: null, anchorVerse: 'Καὶ ὁ λόγος σὰρξ ἐγένετο', anchorReference: 'João 1:14', method: 'Flashcard + Canvas 2D + TPR Digital',          xp: 65,  exercises: 11 },
  { id: 'C1-M05', cycle: 1, order: 5,  title: 'Consoantes Π, Ρ, Μ',                    description: null, anchorVerse: 'ἐν τῷ λόγῳ τῷ ἐμῷ', anchorReference: 'João 8:31',    method: 'Canvas 2D + Ordenar Sílabas + Áudio',          xp: 65,  exercises: 11 },
  { id: 'C1-M06', cycle: 1, order: 6,  title: 'Oclusivas Β, Δ, Γ',                      description: null, anchorVerse: 'κληρονομήσουσιν τὴν γῆν', anchorReference: 'Mateus 5:5', method: 'Canvas 2D + Múltipla Escolha + TPR',          xp: 65,  exercises: 11 },
  { id: 'C1-M07', cycle: 1, order: 7,  title: 'Aspiradas Φ, Χ, Θ',                     description: null, anchorVerse: 'τὸ φῶς τῶν ἀνθρώπων', anchorReference: 'João 1:4',   method: 'Canvas 2D + Flashcard fonético',               xp: 70,  exercises: 11 },
  { id: 'C1-M08', cycle: 1, order: 8,  title: 'Letras Raras Ζ, Ξ, Ψ',                   description: null, anchorVerse: 'ἵνα ζωὴν ἔχωσιν',    anchorReference: 'João 10:10',   method: 'Canvas 2D + Múltipla Escolha + Narração',       xp: 70,  exercises: 11 },
  { id: 'C1-M09', cycle: 1, order: 9,  title: 'Diacríticos e Vogais Longas',            description: null, anchorVerse: 'Αὐτὸς γάρ ἐστιν ἡ εἰρήνη', anchorReference: 'Efésios 2:14', method: 'Flashcard + Áudio comparativo',         xp: 70,  exercises: 8 },
  { id: 'C1-M10', cycle: 1, order: 10, title: 'Revisão Total + João 1:1',               description: null, anchorVerse: 'Ἐν ἀρχῇ ἦν ὁ λόγος', anchorReference: 'João 1:1',     method: 'Quiz + Narração completa',                     xp: 100, exercises: 11 },

  // ─── CICLO II ──────────────────────────────────────
  { id: 'C2-M01', cycle: 2, order: 1, title: 'εἰμί Singular: Eu sou, Tu és, Ele é',    description: null, anchorVerse: 'ἐγώ εἰμι ἡ ἀνάστασις',  anchorReference: 'João 11:25',   method: 'Flashcard + MC + TPR',                          xp: 60,  exercises: 11 },
  { id: 'C2-M02', cycle: 2, order: 2, title: 'εἰμί Plural: Nós somos, Vós sois, Eles são', description: null, anchorVerse: 'ὑμεῖς ἐστε τὸ φῶς', anchorReference: 'Mateus 5:14', method: 'Ordenar + Narração',                            xp: 60,  exercises: 11 },
  { id: 'C2-M03', cycle: 2, order: 3, title: 'Pronomes Pessoais Sujeito',              description: null, anchorVerse: 'ἐγώ εἰμι ὁ ποιμὴν ὁ καλός', anchorReference: 'João 10:11', method: 'TPR Digital + Flashcard',                       xp: 65,  exercises: 11 },
  { id: 'C2-M04', cycle: 2, order: 4, title: 'Artigo Definido (Nominativo)',            description: null, anchorVerse: 'καὶ ὁ λόγος ἦν πρὸς τὸν θεόν', anchorReference: 'João 1:1',  method: 'Ordenar + Preencher Lacuna',                    xp: 65,  exercises: 11 },
  { id: 'C2-M05', cycle: 2, order: 5, title: 'Substantivos Nominativo — 2ª Declinação', description: null, anchorVerse: 'τὸν υἱὸν τὸν μονογενῆ', anchorReference: 'João 3:16',  method: 'Flashcard + Canvas',                            xp: 70,  exercises: 11 },
  { id: 'C2-M06', cycle: 2, order: 6, title: 'Predicado Nominal',                      description: null, anchorVerse: 'ὁ θεὸς ἀγάπη ἐστίν',       anchorReference: '1 João 4:8', method: 'Narração + TBLT',                              xp: 70,  exercises: 11 },
  { id: 'C2-M07', cycle: 2, order: 7, title: 'Verbos: λέγω, ἔχω, πιστεύω',            description: null, anchorVerse: 'ὁ πιστεύων εἰς τὸν υἱόν',  anchorReference: 'João 3:36',  method: 'Flashcard + Ordenar',                           xp: 70,  exercises: 10 },
  { id: 'C2-M08', cycle: 2, order: 8, title: 'Revisão + 1 João 4:8 (Troféu)',          description: null, anchorVerse: 'ὁ θεὸς ἀγάπη ἐστίν',       anchorReference: '1 João 4:8', method: 'Quiz + Narração completa',                      xp: 100, exercises: 12 },

  // ─── CICLO III ─────────────────────────────────────
  { id: 'C3-M01', cycle: 3, order: 1,  title: 'Acusativo — O Objeto Direto',                     description: 'O caso acusativo: marcação do objeto direto na 2ª declinação masculina.', anchorVerse: 'υἱόν',                 anchorReference: 'João 3:16',  method: 'Flashcard + Ordenar Palavras + Preencher Lacuna',  xp: 70,  exercises: 11 },
  { id: 'C3-M02', cycle: 3, order: 2,  title: 'Genitivo — Posse e Origem',                       description: 'O caso genitivo: posse e origem. Terminação -ου e artigo τοῦ/τῆς.',        anchorVerse: 'θεοῦ',                anchorReference: 'João 1:1',   method: 'Flashcard + Ordenar Palavras + Matching Pairs',   xp: 70,  exercises: 11 },
  { id: 'C3-M03', cycle: 3, order: 3,  title: 'Dativo — Objeto Indireto e Instrumento',          description: 'O caso dativo: objeto indireto, instrumento, e lugar. Iota subscrito.',     anchorVerse: 'τῷ θεῷ',             anchorReference: 'João 11:25',  method: 'Flashcard + Preencher Lacuna + TPR Digital',      xp: 70,  exercises: 11 },
  { id: 'C3-M04', cycle: 3, order: 4,  title: 'Revisão dos Casos — João 14:6',                   description: 'Tabela completa do artigo singular e paradigma da 2ª declinação.',          anchorVerse: 'ὁδός (Jo 14:6)',      anchorReference: 'João 14:6',   method: 'Tabela Completa + Ordenar Palavras + SRS',        xp: 75,  exercises: 11 },
  { id: 'C3-M05', cycle: 3, order: 5,  title: 'Substantivos 1ª Declinação Feminina',              description: 'Paradigma da 1ª declinação feminina (-η e -α), artigo feminino.',           anchorVerse: 'ζωή (Jo 14:6)',       anchorReference: 'João 14:6',   method: 'Flashcard + Matching Pairs + Preencher Lacuna',   xp: 70,  exercises: 11 },
  { id: 'C3-M06', cycle: 3, order: 6,  title: 'Declinação Completa — 1ª e 2ª + Neutros',         description: 'Paradigma completo da 2ª declinação (masc e neutro) e 1ª (fem).',           anchorVerse: 'τέκνον (Jo 1:12)',    anchorReference: 'João 1:12',   method: 'Tabela + Flashcard + Ordenar Palavras',           xp: 75,  exercises: 11 },
  { id: 'C3-M07', cycle: 3, order: 7,  title: 'Preposições com Casos',                           description: 'Preposições com acusativo, genitivo e dativo.',                            anchorVerse: 'ἐν (prep mais frequente)', anchorReference: 'João 1:1',  method: 'Flashcard + Matching Pairs + Preencher Lacuna',   xp: 75,  exercises: 11 },
  { id: 'C3-M08', cycle: 3, order: 8,  title: 'Grande Revisão — João 14:6',                       description: 'Revisão completa do Ciclo III com versículo-troféu João 14:6.',             anchorVerse: 'João 14:6',           anchorReference: 'João 14:6',   method: 'SRS Intensivo + Quiz + Aula do Versículo',        xp: 150, exercises: 20 },

  // ─── CICLO IV ──────────────────────────────────────
  { id: 'C4-M01', cycle: 4, order: 1,  title: 'Presente Ativo — O Paradigma λύω',               description: 'Terminações do presente ativo. O aluno conjuga λύω e verbos regulares.',    anchorVerse: 'λύω',                 anchorReference: 'João 1:1',   method: 'Flashcard + Tabela + Preencher Lacuna',           xp: 70,  exercises: 11 },
  { id: 'C4-M02', cycle: 4, order: 2,  title: 'Verbos de Movimento I — ἔρχομαι',                description: 'Introdução aos verbos depoentes com ἔρχομαι e πορεύομαι.',                 anchorVerse: 'ἔρχομαι',             anchorReference: 'João 1:1',   method: 'Flashcard + Ordenar Palavras + Conexão Visual',   xp: 70,  exercises: 11 },
  { id: 'C4-M03', cycle: 4, order: 3,  title: 'Verbos de Movimento II — Compostos',              description: 'Verbos compostos com prefixos: ἀναβαίνω, καταβαίνω, ἐξέρχομαι, εἰσέρχομαι.', anchorVerse: 'ἀναβαίνω',            anchorReference: 'João 1:1',   method: 'Flashcard + Matching Pairs + Preencher Lacuna',   xp: 70,  exercises: 11 },
  { id: 'C4-M04', cycle: 4, order: 4,  title: 'Aula do Versículo — João 14:1–3 (Parte 1)',      description: 'Leitura guiada de João 14:1-3, com foco em πορεύομαι e ἔρχομαι.',          anchorVerse: 'πορεύομαι (Jo 14:2)', anchorReference: 'João 14:1',   method: 'Leitura Guiada + Ordenar Palavras + Interpretação', xp: 75, exercises: 11 },
  { id: 'C4-M05', cycle: 4, order: 5,  title: 'Imperativo Presente',                             description: 'O modo imperativo no presente ativo e depoente, com πιστεύετε.',            anchorVerse: 'πιστεύετε (Jo 14:1)', anchorReference: 'João 14:1',   method: 'Flashcard + Ordenar Palavras + Reconhecimento',   xp: 70,  exercises: 11 },
  { id: 'C4-M06', cycle: 4, order: 6,  title: 'Verbos Contractos',                               description: 'Verbos contractos em -έω, -άω, -όω: contração no presente.',               anchorVerse: 'ποιέω',               anchorReference: 'João 1:1',   method: 'Flashcard + Tabela + Preencher Lacuna',           xp: 75,  exercises: 11 },
  { id: 'C4-M07', cycle: 4, order: 7,  title: 'Voz Média e Depoentes',                           description: 'Terminações médias, depoentes comuns, diferença entre voz ativa e média.',   anchorVerse: 'ἔρχομαι',             anchorReference: 'João 1:1',   method: 'Flashcard + Matching Pairs + Distinção Ativa/Média', xp: 70, exercises: 11 },
  { id: 'C4-M08', cycle: 4, order: 8,  title: 'Grande Revisão — João 14:1–3',                    description: 'Revisão completa do Ciclo IV com versículo-troféu João 14:1-3.',             anchorVerse: 'João 14:1–3',         anchorReference: 'João 1:1',   method: 'Revisão SRS + Quiz + Leitura Guiada',             xp: 150, exercises: 20 },

  // ─── CICLO V ──────────────────────────────────────
  { id: 'C5-M01', cycle: 5, order: 1,  title: 'Adjetivos da 2ª Declinação: ἀγαθός, καλός, πιστός', description: 'Paradigma de adjetivos da 2ª declinação e concordância com substantivos.', anchorVerse: 'ὁ ποιμὴν ὁ καλός', anchorReference: 'João 10:11', method: 'Flashcard + Tabela de Concordância + Preencher Lacuna', xp: 70, exercises: 11 },
  { id: 'C5-M02', cycle: 5, order: 2,  title: 'Adjetivos com 3ª Declinação e Irregularidades',    description: 'μέγας, πολύς, πᾶς — adjetivos irregulares e da 3ª declinação.',             anchorVerse: 'πάντα δι\' αὐτοῦ',  anchorReference: 'João 1:3',   method: 'Flashcard + Matching Pairs + Conexão Visual',     xp: 70, exercises: 11 },
  { id: 'C5-M03', cycle: 5, order: 3,  title: 'Adjetivo Atributivo: ὁ καλὸς ποιμήν',            description: 'Distinção entre construções atributivas e predicativas.',                   anchorVerse: 'ὁ ποιμὴν ὁ καλός', anchorReference: 'João 10:14', method: 'Flashcard + Ordenar Palavras + Distinção Visual', xp: 70, exercises: 11 },
  { id: 'C5-M04', cycle: 5, order: 4,  title: 'Aula do Versículo — Mateus 5:14',                 description: 'ὑμεῖς ἐστε τὸ φῶς τοῦ κόσμου — análise de adjetivos e predicado.',        anchorVerse: 'φῶς',               anchorReference: 'Mateus 5:14', method: 'Leitura Guiada + Análise de Adjetivos',          xp: 75, exercises: 11 },
  { id: 'C5-M05', cycle: 5, order: 5,  title: 'Pronomes Demonstrativos: οὗτος, αὕτη, τοῦτο',    description: 'Paradigma de οὗτος e uso anafórico no NT.',                                anchorVerse: 'οὗτός ἐστιν',       anchorReference: 'Mateus 3:17', method: 'Flashcard + Tabela + Preencher Lacuna',          xp: 70, exercises: 11 },
  { id: 'C5-M06', cycle: 5, order: 6,  title: 'Pronomes Demonstrativos: ἐκεῖνος',               description: 'Paradigma de ἐκεῖνος e distinção οὗτος vs. ἐκεῖνος.',                     anchorVerse: 'ἐκεῖνον δεῖ',       anchorReference: 'João 3:30',   method: 'Flashcard + Matching Pairs + Distinção',         xp: 70, exercises: 11 },
  { id: 'C5-M07', cycle: 5, order: 7,  title: 'Pronomes Relativos: ὅς, ἥ, ὅ',                   description: 'Paradigma do pronome relativo e orações no NT.',                            anchorVerse: 'ὅς',                anchorReference: 'João 1:12',  method: 'Flashcard + Tabela + Análise de Orações',        xp: 75, exercises: 11 },
  { id: 'C5-M08', cycle: 5, order: 8,  title: 'Grande Revisão + Troféu: Mateus 5:14',           description: 'Revisão completa do Ciclo V com versículo-troféu Mt 5:14.',                 anchorVerse: 'ὑμεῖς ἐστε τὸ φῶς', anchorReference: 'Mateus 5:14', method: 'SRS Intensivo + Quiz + Aula do Versículo',      xp: 150, exercises: 20 },

  // ─── CICLO VI ─────────────────────────────────────
  { id: 'C6-M01', cycle: 6, order: 1,  title: 'Aoristo Ativo: Conceito e Tema Sigmático',        description: 'Aspecto perfectivo e terminações -σα do 1º aoristo ativo.',                 anchorVerse: 'ἠγάπησεν',          anchorReference: 'João 3:16',   method: 'Flashcard + Tabela + Preencher Lacuna',          xp: 70, exercises: 11 },
  { id: 'C6-M02', cycle: 6, order: 2,  title: 'Aoristo Temático (2ª Aoristo)',                   description: 'Aoristo sem -σα: ἔλαβον, εἶδον, ἦλθον — mudança de raiz.',                anchorVerse: 'λαβών',             anchorReference: 'João 1:12',  method: 'Flashcard + Matching Pairs + Distinção',         xp: 70, exercises: 11 },
  { id: 'C6-M03', cycle: 6, order: 3,  title: 'Aoristo de Verbos Contractos e Compostos',       description: 'Aoristo de -έω, -άω e verbos compostos com prefixos.',                    anchorVerse: 'ἐποίησεν',          anchorReference: 'João 2:11',   method: 'Flashcard + Tabela + Preencher Lacuna',          xp: 70, exercises: 11 },
  { id: 'C6-M04', cycle: 6, order: 4,  title: 'Aoristo Passivo',                                 description: 'Marca -θη- e terminações ativas secundárias no passivo.',                   anchorVerse: 'ἐβαπτίσθη',         anchorReference: 'Romanos 6:3', method: 'Flashcard + Tabela de Contraste + Preencher',    xp: 70, exercises: 11 },
  { id: 'C6-M05', cycle: 6, order: 5,  title: 'Aula do Versículo — Romanos 6:3-4',               description: 'συνετάφημεν — aoristos que definem a vida cristã.',                        anchorVerse: 'συνετάφημεν',       anchorReference: 'Romanos 6:4', method: 'Leitura Guiada + Análise de Tempos Verbais',     xp: 75, exercises: 11 },
  { id: 'C6-M06', cycle: 6, order: 6,  title: 'Futuro Ativo: Conceito e Formação',               description: 'Marca -σ- e terminações presentes no futuro.',                              anchorVerse: 'πιστεύσω',          anchorReference: 'João 14:3',   method: 'Flashcard + Tabela + Preencher Lacuna',          xp: 70, exercises: 11 },
  { id: 'C6-M07', cycle: 6, order: 7,  title: 'Aula do Versículo — João 14:3',                   description: 'παραλήμψομαι — futuro em promessa profética.',                             anchorVerse: 'παραλήμψομαι',       anchorReference: 'João 14:3',   method: 'Leitura Guiada + Análise de Futuros',            xp: 75, exercises: 11 },
  { id: 'C6-M08', cycle: 6, order: 8,  title: 'Aoristo + Futuro: Revisão Intermediária',         description: 'Tabela comparativa presente × aoristo × futuro.',                          anchorVerse: 'λύω, ἔλυσα, λύσω', anchorReference: 'João 1:1',   method: 'Quiz + Tabela Comparativa + SRS',                xp: 70, exercises: 11 },
  { id: 'C6-M09', cycle: 6, order: 9,  title: 'Leitura Guiada: João 3:14-17',                    description: 'Análise gramatical completa de todos os tempos em Jo 3:14-17.',             anchorVerse: 'ὕψωσεν',            anchorReference: 'João 3:14',   method: 'Leitura Guiada + Análise Gramatical',            xp: 75, exercises: 11 },
  { id: 'C6-M10', cycle: 6, order: 10, title: 'Grande Revisão + Troféu: João 3:14-17',           description: 'Revisão completa do Ciclo VI com versículo-troféu Jo 3:14-17.',             anchorVerse: 'οὕτως γὰρ ἠγάπησεν', anchorReference: 'João 3:16', method: 'SRS Intensivo + Quiz + Aula do Versículo',      xp: 150, exercises: 20 },

  // ─── CICLO VII ────────────────────────────────────
  { id: 'C7-M01', cycle: 7, order: 1,  title: 'Preposições de Direção: εἰς, πρός, κατά',        description: 'Preposições com acusativo para direção e relação.',                        anchorVerse: 'εἰς',               anchorReference: 'João 3:16',   method: 'Flashcard + Mapa Visual + Preencher Lacuna',     xp: 70, exercises: 11 },
  { id: 'C7-M02', cycle: 7, order: 2,  title: 'Aula do Versículo — Atos 1:8',                    description: 'Quatro usos preposicionais em uma passagem missionária.',                   anchorVerse: 'ἐφ\' ὑμᾶς',         anchorReference: 'Atos 1:8',    method: 'Leitura Guiada + Análise de Preposições',        xp: 75, exercises: 11 },
  { id: 'C7-M03', cycle: 7, order: 3,  title: 'Preposições de Origem: ἐκ, ἀπό, πρό',            description: 'ἐκ (origem), ἀπό (separação), πρό (antes) com genitivo.',                 anchorVerse: 'ἐκ',                anchorReference: 'João 1:13',  method: 'Flashcard + Matching Pairs + Preencher Lacuna',  xp: 70, exercises: 11 },
  { id: 'C7-M04', cycle: 7, order: 4,  title: 'Preposições de Meio e Agência: διά, ὑπέρ, περί', description: 'διá (meio/causa), ὑπέρ (benefício), περί (tópico).',                     anchorVerse: 'διά',               anchorReference: 'João 1:3',   method: 'Flashcard + Distinção Casual + Preencher',       xp: 70, exercises: 11 },
  { id: 'C7-M05', cycle: 7, order: 5,  title: 'Preposições com Dativo: ἐν, σύν',                 description: 'ἐν (4 usos: locativo, instrumental, esfera, temporal) e σύν (união).',     anchorVerse: 'ἐν',                anchorReference: 'João 1:3',   method: 'Flashcard + Tabela de Usos + Preencher Lacuna',  xp: 70, exercises: 11 },
  { id: 'C7-M06', cycle: 7, order: 6,  title: 'Preposições com Múltiplos Casos: ἐπί, παρά, μετά', description: 'Preposições que rege 2 ou 3 casos com significados distintos.',            anchorVerse: 'ἐπί',               anchorReference: 'João 1:1',   method: 'Flashcard + Tabela de Casos + Distinção',        xp: 70, exercises: 11 },
  { id: 'C7-M07', cycle: 7, order: 7,  title: 'Partículas de Transição: γάρ, δέ, οὖν, ἀλλά',   description: 'Conectivos pós-positivos e adversativos do NT.',                           anchorVerse: 'γάρ',               anchorReference: 'João 3:16',   method: 'Flashcard + Análise de Contexto + Tradução',     xp: 75, exercises: 11 },
  { id: 'C7-M08', cycle: 7, order: 8,  title: 'Grande Revisão + Troféu: Romanos 8:1',            description: 'Revisão completa do Ciclo VII com versículo-troféu Rm 8:1.',               anchorVerse: 'οὐδὲν ἄρα νῦν',    anchorReference: 'Romanos 8:1',  method: 'SRS Intensivo + Quiz + Aula do Versículo',      xp: 150, exercises: 20 },

  // ─── CICLO VIII ───────────────────────────────────
  { id: 'C8-M01', cycle: 8, order: 1,  title: 'Leitura do Prólogo de João I: João 1:1-5',        description: 'Análise gramatical completa de João 1:1-5 — as palavras mais estudadas.',    anchorVerse: 'Ἐν ἀρχῇ ἦν',       anchorReference: 'João 1:1',   method: 'Leitura Guiada + Análise Versículo a Versículo', xp: 75, exercises: 11 },
  { id: 'C8-M02', cycle: 8, order: 2,  title: 'Leitura do Prólogo de João II: João 1:6-18',      description: 'καὶ ὁ λόγος σὰρξ ἐγένετο — a encarnação em gramática.',                  anchorVerse: 'σὰρξ ἐγένετο',      anchorReference: 'João 1:14',  method: 'Leitura Guiada + Análise Gramatical + Teologia', xp: 75, exercises: 11 },
  { id: 'C8-M03', cycle: 8, order: 3,  title: 'Leitura de 1 João 4:7-21 I',                      description: 'A fonte do amor — ἀγαπῶμεν, ἐκ τοῦ θεοῦ, ἠγάπησεν.',                    anchorVerse: 'ἀγαπῶμεν',          anchorReference: '1 João 4:7',  method: 'Leitura Guiada + Identificação de Estruturas',   xp: 75, exercises: 11 },
  { id: 'C8-M04', cycle: 8, order: 4,  title: 'Leitura de 1 João 4:7-21 II',                     description: 'Amor e medo — φόβος οὐκ ἔστιν ἐν τῇ ἀγάπῃ.',                            anchorVerse: 'φόβος οὐκ ἔστιν',   anchorReference: '1 João 4:18', method: 'Leitura Guiada + Análise de Contraste',          xp: 75, exercises: 11 },
  { id: 'C8-M05', cycle: 8, order: 5,  title: 'Leitura de Romanos 8:1-11 I',                     description: 'οὐδὲν κατάκριμα — condenação, lei do Espírito, carne vs. espírito.',      anchorVerse: 'οὐδὲν κατάκριμα',  anchorReference: 'Romanos 8:1',  method: 'Leitura Guiada + Análise de Contraste',          xp: 75, exercises: 11 },
  { id: 'C8-M06', cycle: 8, order: 6,  title: 'Leitura de Romanos 8:1-11 II',                    description: 'Síntese de Rm 8:1-11 — estrutura quiástica e conexões intertextuais.',     anchorVerse: 'πνεῦμα ζωῆς',       anchorReference: 'Romanos 8:2',  method: 'Leitura Guiada + Síntese + Conexão',            xp: 75, exercises: 11 },
  { id: 'C8-M07', cycle: 8, order: 7,  title: 'Leitura Livre com Leitor Interlinear',            description: 'O aluno escolhe uma passagem do NT e a lê com análise gramatical.',        anchorVerse: 'λόγος',             anchorReference: 'João 1:1',   method: 'Leitor Interlinear + Escolha do Aluno',          xp: 100, exercises: 11 },
  { id: 'C8-M08', cycle: 8, order: 8,  title: 'Grande Revisão + Troféu: Filipenses 4:13',       description: 'Revisão final de todos os ciclos I-VIII e versículo-troféu Fp 4:13.',       anchorVerse: 'πάντα ἰσχύω',       anchorReference: 'Filipenses 4:13', method: 'SRS Final + Quiz + Aula do Versículo Troféu', xp: 150, exercises: 20 },
];

export const CYCLE_1_MODULES = MODULES.filter((m) => m.cycle === 1);
export const CYCLE_2_MODULES = MODULES.filter((m) => m.cycle === 2);
export const CYCLE_3_MODULES = MODULES.filter((m) => m.cycle === 3);
export const CYCLE_4_MODULES = MODULES.filter((m) => m.cycle === 4);
export const CYCLE_5_MODULES = MODULES.filter((m) => m.cycle === 5);
export const CYCLE_6_MODULES = MODULES.filter((m) => m.cycle === 6);
export const CYCLE_7_MODULES = MODULES.filter((m) => m.cycle === 7);
export const CYCLE_8_MODULES = MODULES.filter((m) => m.cycle === 8);
