// src/constants/routes.ts
export const ROUTES = {
  SPLASH: '/splash',
  ONBOARDING: '/onboarding',
  AUTH: '/auth',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  TRAIL: '/trail',
  TRAIL_UNIT: '/trail/unit/:unitId',
  LESSON: '/lesson/:lessonId',
  CANVAS: '/canvas/:letterId',
  READER: '/reader',
  READER_PASSAGE: '/reader/:book/:chapter/:verse',
  REVIEW: '/review',
  REVIEW_SESSION: '/review/session',
  PROFILE: '/profile',
  PROFILE_ACHIEVEMENTS: '/profile/achievements',
  SETTINGS: '/settings',
  PAYWALL: '/paywall',
} as const;
