// src/content/nt/glossarySeed.ts
// Glosses manuais em PT-BR para as palavras gregas mais frequentes do NT.
// Usado por buildGlossary.ts e buildInterlinear.ts como base autoritativa.
//
// Formato: chave = lemma grego (lowercase) -> gloss PT curto (1-3 palavras).
//
// Estas glosses são PRODUÇÃO ORIGINAL da equipe Koiné, não reproduções
// de traduções copyrighted. São idiomáticas, didáticas, otimizadas para
// leitura interlinear.
//
// Para adicionar uma nova palavra: inclua o lemma grego em lowercase como chave,
// e o gloss PT como valor. Duplicatas são resolvidas (último valor vence).

export interface GlossaryEntry {
  lemma: string;
  gloss: string;
  parsing?: string;
}

// Lista de glosses — armazenada como array de tuplas e mesclada em runtime.
// Isso evita conflitos de "duplicate property" do TypeScript.
const GLOSS_LIST: Array<[string, string]> = [
  // ─── PRONOMES ─────────────────────────────────────────────
  ['ὁ', 'o'],
  ['ἡ', 'a'],
  ['τό', 'o/a'],
  ['τοῦ', 'de o'],
  ['τῆς', 'de a'],
  ['τῷ', 'para o'],
  ['τῇ', 'para a'],
  ['τὸν', 'o (ac)'],
  ['τήν', 'a (ac)'],
  ['τῶν', 'dos'],
  ['τοῖς', 'aos'],
  ['ταῖς', 'às'],
  ['τούς', 'os (ac)'],
  ['τάς', 'as (ac)'],
  ['αὐτός', 'ele mesmo'],
  ['αὐτοῦ', 'dele'],
  ['αὐτῷ', 'a ele'],
  ['αὐτόν', 'ele (ac)'],
  ['αὐτῶν', 'deles'],
  ['αὐτοῖς', 'a eles'],
  ['αὐτούς', 'eles (ac)'],
  ['αὐτή', 'ela mesma'],
  ['αὐτῆς', 'dela'],
  ['αὐτήν', 'ela (ac)'],
  ['αὐτό', 'isso'],
  ['ἐγώ', 'eu'],
  ['μου', 'de mim'],
  ['μοι', 'a mim'],
  ['με', 'me'],
  ['ἡμῶν', 'de nós'],
  ['ἡμῖν', 'a nós'],
  ['ἡμᾶς', 'nós (ac)'],
  ['σύ', 'tu'],
  ['σου', 'de ti'],
  ['σοι', 'a ti'],
  ['σε', 'te'],
  ['ὑμῶν', 'de vós'],
  ['ὑμῖν', 'a vós'],
  ['ὑμᾶς', 'vós (ac)'],
  ['οὗτος', 'este'],
  ['τούτου', 'deste'],
  ['τούτῳ', 'a este'],
  ['τοῦτον', 'este (ac)'],
  ['αὕτη', 'esta'],
  ['ταύτης', 'desta'],
  ['ταύτην', 'esta (ac)'],
  ['τοῦτο', 'isto'],
  ['ἐκεῖνος', 'aquele'],
  ['ἐκείνου', 'daquele'],
  ['πᾶς', 'todo'],
  ['πᾶσα', 'toda'],
  ['πᾶν', 'tudo'],
  ['πάντα', 'todas'],
  ['πάντων', 'de todos'],
  ['πᾶσιν', 'a todos'],
  ['πάντας', 'todos (ac)'],
  ['πάσης', 'de toda'],
  ['πάσῃ', 'em toda'],
  ['πᾶσαν', 'toda (ac)'],

  // ─── PREPOSIÇÕES ──────────────────────────────────────────
  ['ἐν', 'em'],
  ['εἰς', 'para'],
  ['ἐκ', 'de'],
  ['ἀπό', 'de'],
  ['πρός', 'com/para'],
  ['πρὸς', 'com/para'],
  ['μετά', 'com'],
  ['μετὰ', 'com'],
  ['διά', 'por/meio de'],
  ['διὰ', 'por/meio de'],
  ['κατά', 'segundo'],
  ['κατὰ', 'segundo'],
  ['ὑπό', 'por'],
  ['ὑπὲρ', 'por/em favor de'],
  ['περί', 'sobre'],
  ['περὶ', 'sobre'],
  ['ἐπί', 'sobre'],
  ['ἐπὶ', 'sobre'],
  ['σύν', 'com'],
  ['σὺν', 'com'],
  ['ἀντί', 'em vez de'],
  ['ἀντὶ', 'em vez de'],
  ['παρά', 'junto a'],
  ['παρὰ', 'junto a'],
  ['ἄχρι', 'até'],
  ['μέχρι', 'até'],

  // ─── CONJUNÇÕES E PARTÍCULAS ──────────────────────────────
  ['καί', 'e'],
  ['καὶ', 'e'],
  ['ἀλλά', 'mas'],
  ['ἀλλὰ', 'mas'],
  ['δέ', 'porém'],
  ['δὲ', 'porém'],
  ['ἤ', 'ou'],
  ['ἢ', 'ou'],
  ['οὖν', 'portanto'],
  ['γάρ', 'porque'],
  ['γὰρ', 'porque'],
  ['εἰ', 'se'],
  ['ἵνα', 'para que'],
  ['ὅτι', 'que/porque'],
  ['ὅταν', 'quando'],
  ['ὅτε', 'quando'],
  ['ὡς', 'como'],
  ['ὥστε', 'de modo que'],
  ['ἐάν', 'se'],
  ['ἐὰν', 'se'],
  ['μή', 'não'],
  ['μὴ', 'não'],
  ['οὐ', 'não'],
  ['οὐκ', 'não'],
  ['οὐχ', 'não'],
  ['οὐδέ', 'nem'],
  ['οὐδὲ', 'nem'],
  ['μηδέ', 'nem'],
  ['μηδὲ', 'nem'],
  ['μέν', 'por um lado'],
  ['μὲν', 'por um lado'],
  ['ἀληθῶς', 'verdadeiramente'],
  ['ἀμήν', 'amém'],
  ['ἀμὴν', 'amém'],

  // ─── VERBOS ESSENCIAIS ────────────────────────────────────
  ['εἰμί', 'ser/estar'],
  ['ἐστί', 'é'],
  ['ἐστι', 'é'],
  ['ἐστιν', 'é'],
  ['ἦν', 'era'],
  ['ἦσαν', 'eram'],
  ['ἐσμέν', 'somos'],
  ['ἐστέ', 'sois'],
  ['ἐστε', 'sois'],
  ['εἰσί', 'são'],
  ['εἰσι', 'são'],
  ['εἰσιν', 'são'],
  ['ἔσομαι', 'serei'],
  ['ἔσῃ', 'serás'],
  ['ἔσται', 'será'],
  ['ἐσόμεθα', 'seremos'],
  ['ἔσεσθε', 'sereis'],
  ['ἔσονται', 'serão'],
  ['λέγω', 'dizer'],
  ['λέγει', 'diz'],
  ['λέγουσι', 'dizem'],
  ['λέγουσιν', 'dizem'],
  ['λέγομεν', 'dizemos'],
  ['ἔλεγεν', 'dizia'],
  ['ἔλεγον', 'diziam'],
  ['εἶπεν', 'disse'],
  ['εἶπε', 'disse'],
  ['εἶπέ', 'disse'],
  ['εἶπον', 'disseram'],
  ['εἴπῃ', 'diga'],
  ['εἴπωσιν', 'digam'],
  ['ἀποκρίνομαι', 'responder'],
  ['ἀπεκρίθη', 'respondeu'],
  ['ἀπεκρίθησαν', 'responderam'],
  ['ἀπεκρίνατο', 'respondeu'],
  ['γίνομαι', 'tornar-se/acontecer'],
  ['γίνεται', 'torna-se'],
  ['γίνεσθε', 'tornai-vos'],
  ['ἐγένετο', 'tornou-se/aconteceu'],
  ['γενέσθαι', 'tornar-se'],
  ['γενομένου', 'tornando-se'],
  ['γίνονται', 'tornam-se'],
  ['γίνεσθαι', 'tornar-se'],
  ['γενόμενος', 'tendo se tornado'],
  ['γενομένη', 'tendo se tornado (fem)'],
  ['γενόμενον', 'tornado'],
  ['γίνωσκε', 'conhece!'],
  ['ποιέω', 'fazer'],
  ['ποιεῖ', 'faz'],
  ['ποιοῦσι', 'fazem'],
  ['ποιήσῃ', 'faça'],
  ['ποιήσει', 'fará'],
  ['ἐποίησεν', 'fez'],
  ['ἐποίησα', 'fiz'],
  ['ἐποιήσαμεν', 'fizemos'],
  ['ποιῆτε', 'façais'],
  ['ποιοῦμεν', 'fazemos'],
  ['ποιεῖτε', 'fazeis'],
  ['ποιήσω', 'farei'],
  ['ποιήσουσι', 'farão'],
  ['ποιήσωσι', 'façam'],
  ['ποιήσατε', 'fazei'],
  ['ποιήσῃς', 'faças'],
  ['ποιοῦντα', 'fazendo'],
  ['ποιῶν', 'fazendo'],
  ['ποιοῦντες', 'fazendo (pl)'],
  ['ἐποίησας', 'fizeste'],
  ['ἐποιήσατε', 'fizestes'],
  ['ἐποίησαν', 'fizeram'],
  ['ποιήσας', 'tendo feito'],
  ['ποιήσαντες', 'tendo feito (pl)'],
  ['ἔχω', 'ter'],
  ['ἔχει', 'tem'],
  ['ἔχομεν', 'temos'],
  ['ἔχουσι', 'têm'],
  ['ἔχετε', 'tendes'],
  ['εἶχεν', 'tinha'],
  ['εἶχον', 'tinham'],
  ['σχῇ', 'tenha'],
  ['ἔχων', 'tendo'],
  ['λαμβάνω', 'receber/tomar'],
  ['λαμβάνει', 'recebe'],
  ['λαμβάνομεν', 'recebemos'],
  ['λάβῃ', 'receba'],
  ['λάβωσι', 'recebam'],
  ['ἔλαβεν', 'recebeu'],
  ['ἔλαβον', 'receberam'],
  ['λαβών', 'tendo recebido'],
  ['λαμβάνουσι', 'recebem'],
  ['λαμβάνετε', 'recebeis'],
  ['λάβω', 'receba'],
  ['λάβετε', 'recebei'],
  ['λαβοῦσα', 'tendo recebido (fem)'],
  ['λαβόντες', 'tendo recebido (pl)'],
  ['λάβε', 'recebe!'],
  ['ἔλαβαν', 'receberam'],
  ['ἔλαβε', 'recebeu'],
  ['ἔλαβες', 'recebeste'],
  ['ἐλάβομεν', 'recebemos'],
  ['ἐλάβετε', 'recebestes'],
  ['δίδωμι', 'dar'],
  ['δίδωσιν', 'dá'],
  ['δίδωσι', 'dá'],
  ['δώσει', 'dará'],
  ['δώσῃ', 'dê'],
  ['δοῦναι', 'dar'],
  ['δούς', 'tendo dado'],
  ['ἔδωκεν', 'deu'],
  ['ἔδωκα', 'dei'],
  ['ἔδωκας', 'deste'],
  ['δέδωκεν', 'tem dado'],
  ['δέδωκα', 'tenho dado'],
  ['δίδομεν', 'damos'],
  ['δίδοτε', 'dais'],
  ['διδόασι', 'dão'],
  ['διδόασιν', 'dão'],
  ['δώσω', 'darei'],
  ['δώσομεν', 'daremos'],
  ['δώσετε', 'dareis'],
  ['δώσουσι', 'darão'],
  ['δώσουσιν', 'darão'],
  ['δώσωσι', 'deem'],
  ['δώσωσιν', 'deem'],
  ['δοῦναί', 'dar'],
  ['δόντες', 'tendo dado (pl)'],
  ['δοῦσα', 'tendo dado (fem)'],
  ['ἔδωκα ', 'dei'],
  ['ἔδωκε', 'deu'],
  ['ἔδωκαν', 'deram'],
  ['δέδωκας', 'tens dado'],
  ['δέδωκε', 'tem dado'],
  ['δέδωκαν', 'têm dado'],
  ['δεδώκει', 'tinha dado'],
  ['ἀγαπάω', 'amar'],
  ['ἀγαπᾷ', 'ama'],
  ['ἀγαπῶσιν', 'amam'],
  ['ἠγάπησεν', 'amou'],
  ['ἠγαπήκαμεν', 'temos amado'],
  ['ἠγαπημένος', 'amado'],
  ['ἀγαπητός', 'amado'],
  ['ἀγαπητοί', 'amados'],
  ['πιστεύω', 'crer'],
  ['πιστεύει', 'crê'],
  ['πιστεύομεν', 'cremos'],
  ['πιστεύσῃ', 'creia'],
  ['πιστεύσουσι', 'crerão'],
  ['πιστεύσας', 'tendo crido'],
  ['ἐπίστευσεν', 'creu'],
  ['ἐπίστευσαν', 'creram'],
  ['πιστεύων', 'crendo'],
  ['βλέπω', 'ver'],
  ['βλέπει', 'vê'],
  ['βλέπουσι', 'veem'],
  ['βλέπετε', 'vedes'],
  ['βλέψῃ', 'veja'],
  ['ἔβλεπεν', 'via'],
  ['εἶδεν', 'viu'],
  ['ἰδών', 'tendo visto'],
  ['ἰδοὺ', 'eis'],
  ['ἰδού', 'eis'],
  ['ὁράω', 'ver'],
  ['ὁρᾷ', 'vê'],
  ['ὁρῶσι', 'veem'],
  ['ἑωράκαμεν', 'temos visto'],
  ['οἶδα', 'saber'],
  ['οἶδας', 'sabes'],
  ['οἶδεν', 'sabe'],
  ['οἴδαμεν', 'sabemos'],
  ['οἴδατε', 'sabeis'],
  ['οἴδασι', 'sabem'],
  ['ἤδει', 'sabia'],
  ['ᾔδει', 'sabia'],
  ['ᾔδεισαν', 'sabiam'],
  ['γινώσκω', 'conhecer'],
  ['γινώσκει', 'conhece'],
  ['γινώσκομεν', 'conhecemos'],
  ['γινώσκουσι', 'conhecem'],
  ['ἔγνω', 'conheceu'],
  ['ἔγνωσαν', 'conheceram'],
  ['γνῶτε', 'conheçais'],
  ['ἀκούω', 'ouvir'],
  ['ἀκούει', 'ouve'],
  ['ἀκούομεν', 'ouvimos'],
  ['ἀκούουσι', 'ouvem'],
  ['ἀκούσῃ', 'ouça'],
  ['ἀκούσας', 'tendo ouvido'],
  ['ἤκουσεν', 'ouviu'],
  ['ἤκουσα', 'ouvi'],
  ['ἤκουσαν', 'ouviram'],
  ['ἀκολουθέω', 'seguir'],
  ['ἀκολουθεῖ', 'segue'],
  ['ἀκολουθοῦσι', 'seguem'],
  ['ἀκολουθήσω', 'seguirei'],
  ['ἀκολουθήσει', 'seguirá'],
  ['ἠκολούθησεν', 'seguiu'],
  ['ἠκολούθησαν', 'seguiram'],
  ['ἀκολουθῶν', 'seguindo'],
  ['ἔρχομαι', 'vir'],
  ['ἔρχεται', 'vem'],
  ['ἔρχονται', 'vêm'],
  ['ἔρχου', 'vem'],
  ['ἔλθῃ', 'venha'],
  ['ἔλθωσι', 'venham'],
  ['ἦλθεν', 'veio'],
  ['ἦλθον', 'vieram'],
  ['ἐλθών', 'tendo vindo'],
  ['ἐλθεῖν', 'vir'],
  ['ἀπέρχομαι', 'ir embora'],
  ['ἀπῆλθεν', 'foi embora'],
  ['ἀπῆλθον', 'foram embora'],
  ['πορεύομαι', 'ir'],
  ['πορεύεται', 'vai'],
  ['πορευθείς', 'tendo ido'],
  ['ἐπορεύθη', 'foi'],
  ['ἐπορεύθησαν', 'foram'],
  ['εἰσέρχομαι', 'entrar'],
  ['εἰσῆλθεν', 'entrou'],
  ['εἰσῆλθον', 'entraram'],
  ['ἐξέρχομαι', 'sair'],
  ['ἐξῆλθεν', 'saiu'],
  ['ἐξῆλθον', 'saíram'],
  ['ἐξελθών', 'tendo saído'],
  ['λαλέω', 'falar'],
  ['λαλεῖ', 'fala'],
  ['λαλοῦσι', 'falam'],
  ['λαλήσω', 'falarei'],
  ['ἐλάλησεν', 'falou'],
  ['ἐλάλουν', 'falavam'],
  ['λαλῶν', 'falando'],
  ['λαλῆσαι', 'falar'],
  ['ὁμολογέω', 'confessar'],
  ['ὁμολογεῖ', 'confessa'],
  ['ὁμολογοῦμεν', 'confessamos'],
  ['ὡμολόγησεν', 'confessou'],
  ['ἁμαρτάνω', 'pecar'],
  ['ἁμαρτάνει', 'peca'],
  ['ἥμαρτεν', 'pecou'],
  ['ἥμαρτον', 'pecaram'],
  ['ἁμαρτωλός', 'pecador'],
  ['ἁμαρτωλοί', 'pecadores'],
  ['ἁμαρτία', 'pecado'],
  ['ἁμαρτίαι', 'pecados'],
  ['ἁμαρτίαν', 'pecado (ac)'],
  ['ἁμαρτίας', 'de pecados'],
  ['ἁμαρτιῶν', 'de pecados'],
  ['ἁμαρτίαις', 'em pecados'],

  // ─── SUBSTANTIVOS TEOLÓGICOS ESSENCIAIS ──────────────────
  ['θεός', 'Deus'],
  ['θεοῦ', 'de Deus'],
  ['θεῷ', 'a Deus'],
  ['θεόν', 'Deus (ac)'],
  ['θεοί', 'deuses'],
  ['χριστός', 'Cristo'],
  ['Χριστός', 'Cristo'],
  ['Χριστοῦ', 'de Cristo'],
  ['Χριστῷ', 'a Cristo'],
  ['Χριστόν', 'Cristo (ac)'],
  ['Ἰησοῦς', 'Jesus'],
  ['Ἰησοῦ', 'de Jesus'],
  ['Ἰησοῦν', 'Jesus (ac)'],
  ['κύριος', 'Senhor'],
  ['κυρίου', 'do Senhor'],
  ['κυρίῳ', 'ao Senhor'],
  ['κύριον', 'Senhor (ac)'],
  ['κύριε', 'Senhor (voc)'],
  ['κύριοι', 'senhores'],
  ['πνεῦμα', 'Espírito'],
  ['πνεύματος', 'do Espírito'],
  ['πνεύματι', 'em Espírito'],
  ['λόγος', 'Verbo/Palavra'],
  ['λόγου', 'do Verbo'],
  ['λόγῳ', 'no Verbo'],
  ['λόγον', 'Verbo (ac)'],
  ['λόγοι', 'palavras'],
  ['λόγοις', 'em palavras'],
  ['λόγων', 'de palavras'],
  ['ἀγάπη', 'amor'],
  ['ἀγάπης', 'de amor'],
  ['ἀγάπῃ', 'em amor'],
  ['ἀγάπην', 'amor (ac)'],
  ['ζωή', 'vida'],
  ['ζωῆς', 'de vida'],
  ['ζωῇ', 'em vida'],
  ['ζωήν', 'vida (ac)'],
  ['ζωὴ', 'vida'],
  ['ζωὴν', 'vida (ac)'],
  ['θάνατος', 'morte'],
  ['θανάτου', 'de morte'],
  ['θάνατον', 'morte (ac)'],
  ['θανάτῳ', 'em morte'],
  ['κόσμος', 'mundo'],
  ['κόσμου', 'do mundo'],
  ['κόσμῳ', 'no mundo'],
  ['κόσμον', 'mundo (ac)'],
  ['κόσμοι', 'mundos'],
  ['φῶς', 'luz'],
  ['φωτός', 'de luz'],
  ['φωτί', 'em luz'],
  ['σκοτία', 'trevas'],
  ['σκοτίᾳ', 'em trevas'],
  ['σκοτίαν', 'trevas (ac)'],
  ['σκότος', 'trevas'],
  ['ἀλήθεια', 'verdade'],
  ['ἀληθείας', 'de verdade'],
  ['ἀληθείᾳ', 'em verdade'],
  ['ἀλήθειαν', 'verdade (ac)'],
  ['ἀληθής', 'verdadeiro'],
  ['ἀληθινός', 'verdadeiro'],
  ['πίστις', 'fé'],
  ['πίστεως', 'de fé'],
  ['πίστει', 'em fé'],
  ['πίστιν', 'fé (ac)'],
  ['πιστός', 'fiel'],
  ['πιστοί', 'fiéis'],
  ['πιστόν', 'fiel (ac)'],
  ['πιστοῦ', 'de fiel'],
  ['ἀγαθός', 'bom'],
  ['ἀγαθή', 'boa'],
  ['ἀγαθόν', 'bom (ac)'],
  ['ἀγαθοί', 'bons'],
  ['ἀγαθά', 'boas'],
  ['καλός', 'belo/bom'],
  ['καλόν', 'bom'],
  ['πονηρός', 'mau'],
  ['πονηροί', 'maus'],
  ['πονηρόν', 'mau (ac)'],
  ['κακός', 'mau'],
  ['κακά', 'males'],
  ['δίκαιος', 'justo'],
  ['δικαίου', 'de justo'],
  ['δίκαιοι', 'justos'],
  ['δικαιοσύνη', 'justiça'],
  ['δικαιοσύνης', 'de justiça'],
  ['δικαιοσύνην', 'justiça (ac)'],
  ['χάρις', 'graça'],
  ['χάριτος', 'de graça'],
  ['χάριτι', 'em graça'],
  ['χάριν', 'graça (ac)'],
  ['ἔλεος', 'misericórdia'],
  ['ἐλέους', 'de misericórdia'],
  ['ἔλεον', 'misericórdia (ac)'],
  ['ἔργον', 'obra'],
  ['ἔργα', 'obras'],
  ['ἔργων', 'de obras'],
  ['ἔργοις', 'em obras'],
  ['ἀρχή', 'princípio'],
  ['ἀρχῆς', 'de princípio'],
  ['ἀρχῇ', 'em princípio'],
  ['ἀρχήν', 'princípio (ac)'],
  ['ἀρχαί', 'princípios'],
  ['υἱός', 'filho'],
  ['υἱοῦ', 'de filho'],
  ['υἱῷ', 'a filho'],
  ['υἱόν', 'filho (ac)'],
  ['υἱοί', 'filhos'],
  ['πατήρ', 'pai'],
  ['πατρός', 'de pai'],
  ['πατρί', 'a pai'],
  ['πατέρα', 'pai (ac)'],
  ['πατέρες', 'pais'],
  ['πατράσι', 'pais (dat)'],
  ['ἀδελφός', 'irmão'],
  ['ἀδελφοί', 'irmãos'],
  ['ἀδελφοῦ', 'de irmão'],
  ['ἀδελφῶν', 'de irmãos'],
  ['ἀδελφόν', 'irmão (ac)'],
  ['ἀδελφοὺς', 'irmãos (ac)'],
  ['ἀδελφοῖς', 'aos irmãos'],
  ['μήτηρ', 'mãe'],
  ['μητρός', 'de mãe'],
  ['μητέρα', 'mãe (ac)'],
  ['γυνή', 'mulher'],
  ['γυναικός', 'de mulher'],
  ['γυναικί', 'a mulher'],
  ['γυναῖκα', 'mulher (ac)'],
  ['γυναῖκες', 'mulheres'],
  ['ἀνήρ', 'homem'],
  ['ἀνδρός', 'de homem'],
  ['ἀνδρί', 'a homem'],
  ['ἄνδρα', 'homem (ac)'],
  ['ἄνδρες', 'homens'],
  ['ἀνθρώπου', 'de homem'],
  ['ἄνθρωπος', 'homem'],
  ['ἄνθρωπε', 'homem (voc)'],
  ['ἄνθρωποι', 'homens'],
  ['ἀνθρώπων', 'de homens'],
  ['ἀνθρώποις', 'aos homens'],
  ['ἀνθρώπους', 'homens (ac)'],
  ['τέκνον', 'filho (criança)'],
  ['τέκνα', 'filhos'],
  ['τέκνοις', 'a filhos'],
  ['τέκνων', 'de filhos'],
  ['τέκνου', 'de filho'],
  ['οἶκος', 'casa'],
  ['οἴκου', 'de casa'],
  ['οἴκῳ', 'em casa'],
  ['οἶκον', 'casa (ac)'],
  ['οἰκίᾳ', 'em casa'],
  ['οἰκίαν', 'casa (ac)'],
  ['πόλις', 'cidade'],
  ['πόλεως', 'de cidade'],
  ['πόλιν', 'cidade (ac)'],
  ['πόλει', 'em cidade'],
  ['ἱερόν', 'templo'],
  ['ἱεροῦ', 'de templo'],
  ['ἱερῷ', 'em templo'],

  // ─── NOMES PRÓPRIOS FREQUENTES ────────────────────────────
  ['Ἰουδαῖος', 'judeu'],
  ['Ἰουδαῖοι', 'judeus'],
  ['Ἰουδαίων', 'de judeus'],
  ['Ἰουδαίοις', 'a judeus'],
  ['Ἰουδαίους', 'judeus (ac)'],
  ['Ἰουδαίαν', 'Judeia (ac)'],
  ['Ἰουδαία', 'Judeia'],
  ['Ἰουδαίας', 'de Judeia'],
  ['Ἱερουσαλήμ', 'Jerusalém'],
  ['Ἱεροσόλυμα', 'Jerusalém'],
  ['Ἱεροσολύμων', 'de Jerusalém'],
  ['Ἱεροσολύμοις', 'em Jerusalém'],
  ['Γαλιλαία', 'Galileia'],
  ['Γαλιλαίας', 'de Galileia'],
  ['Γαλιλαίᾳ', 'em Galileia'],
  ['Γαλιλαίαν', 'Galileia (ac)'],
  ['Σαμαρίτης', 'samaritano'],
  ['Σαμαρίτας', 'samaritano (ac)'],
  ['Ἕλλην', 'grego'],
  ['Ἕλληνες', 'gregos'],
  ['Ἑλλήνων', 'de gregos'],
  ['Ἕλλησι', 'aos gregos'],
  ['Ἕλληνας', 'gregos (ac)'],
  ['Ῥωμαῖος', 'romano'],
  ['Ῥωμαῖοι', 'romanos'],
  ['Μωϋσῆς', 'Moisés'],
  ['Μωϋσέως', 'de Moisés'],
  ['Μωϋσεῖ', 'a Moisés'],
  ['Μωϋσέα', 'Moisés (ac)'],
  ['Ἀβραάμ', 'Abraão'],
  ['Ἀβραὰμ', 'Abraão'],
  ['Δαυίδ', 'Davi'],
  ['Ἰσραήλ', 'Israel'],
  ['Ἰσραὴλ', 'Israel'],
  ['Παῦλος', 'Paulo'],
  ['Παύλου', 'de Paulo'],
  ['Παύλῳ', 'a Paulo'],
  ['Παῦλον', 'Paulo (ac)'],
  ['Παῦλε', 'Paulo (voc)'],
  ['Πέτρος', 'Pedro'],
  ['Πέτρου', 'de Pedro'],
  ['Πέτρῳ', 'a Pedro'],
  ['Πέτρον', 'Pedro (ac)'],
  ['Πέτρε', 'Pedro (voc)'],
  ['Σίμων', 'Simão'],
  ['Συμεών', 'Simão'],
  ['Ἰάκωβος', 'Tiago'],
  ['Ἰωάννης', 'João'],
  ['Ἰωάννου', 'de João'],
  ['Ἰωάννῃ', 'a João'],
  ['Ἰωάννην', 'João (ac)'],

  // ─── TOP PENDENTES (F0.3) ────────────────────────────────
  ['τις', 'algum'],
  ['τινα', 'algum (ac)'],
  ['τινος', 'de algum'],
  ['τινι', 'a algum'],
  ['τινες', 'alguns'],
  ['τινων', 'de alguns'],
  ['τισι', 'a alguns'],
  ['τινάς', 'alguns (ac)'],
  ['ὅς', 'que/qual'],
  ['ἥ', 'que (fem)'],
  ['ὅ', 'que (neut)'],
  ['οὗ', 'de quem'],
  ['ᾗ', 'em que'],
  ['ὧν', 'de quem (pl)'],
  ['οἷς', 'a quem (pl)'],
  ['οὕς', 'quem (ac pl)'],
  ['ἅς', 'que (ac pl fem)'],
  ['τέ', 'e'],
  ['τε', 'e'],
  ['οὕτως', 'assim'],
  ['οὕτω', 'assim'],
  ['καθώς', 'conforme'],
  ['καθὼς', 'conforme'],
  ['ἄν', 'talvez'],
  ['ὑπέρ', 'por/em favor de'],
  ['ἕως', 'até'],
  ['γῆ', 'terra'],
  ['γῆς', 'de terra'],
  ['γῆν', 'terra (ac)'],
  ['γράφω', 'escrever'],
  ['γράφει', 'escreve'],
  ['γράφουσι', 'escrevem'],
  ['γράψω', 'escreverei'],
  ['γράψῃ', 'escreva'],
  ['γράψον', 'escreve!'],
  ['ἔγραψεν', 'escreveu'],
  ['ἔγραψα', 'escrevi'],
  ['γραφή', 'Escritura'],
  ['γραφαί', 'Escrituras'],
  ['γραφαῖς', 'em Escrituras'],
  ['γραφήν', 'Escritura (ac)'],
  ['γραφῶν', 'de Escrituras'],
  ['θέλω', 'querer'],
  ['θέλει', 'quer'],
  ['θέλομεν', 'queremos'],
  ['θέλουσι', 'querem'],
  ['θέλετε', 'quereis'],
  ['θελήσῃ', 'queira'],
  ['θελήσει', 'quererá'],
  ['θελήσω', 'quererei'],
  ['ἠθέλησεν', 'quis'],
  ['ἠθέλησα', 'quis'],
  ['ἠθέλομεν', 'queríamos'],
  ['δύναμαι', 'poder'],
  ['δύναται', 'pode'],
  ['δυνάμεθα', 'podemos'],
  ['δύνανται', 'podem'],
  ['δύνασθε', 'podeis'],
  ['δυνήσῃ', 'possa'],
  ['δυνήσεσθε', 'podereis'],
  ['ἠδύνατο', 'podia'],
  ['ἠδύναντο', 'podiam'],
  ['δυνατός', 'poderoso'],
  ['δυνατόν', 'possível'],
  ['δυνατά', 'poderosas'],
  ['δύναμις', 'poder'],
  ['δυνάμεως', 'de poder'],
  ['δυνάμει', 'em poder'],
  ['δυνάμεις', 'poderes'],
  ['δυνάμεσι', 'em poderes'],
  ['δέω', 'prender/necessitar'],
  ['δεῖ', 'é necessário'],
  ['ἔδει', 'era necessário'],
  ['δέον', 'necessário'],
  ['μαθητής', 'discípulo'],
  ['μαθηταί', 'discípulos'],
  ['μαθητοῦ', 'de discípulo'],
  ['μαθητῶν', 'de discípulos'],
  ['μαθηταῖς', 'aos discípulos'],
  ['μαθητάς', 'discípulos (ac)'],
  ['μαθητῇ', 'a discípulo'],
  ['μαθητήν', 'discípulo (ac)'],
  ['οὐδείς', 'nenhum'],
  ['οὐδένα', 'nenhum (ac)'],
  ['οὐδενός', 'de nenhum'],
  ['οὐδενί', 'a nenhum'],
  ['οὐδέν', 'nada'],
  ['ὄνομα', 'nome'],
  ['ὀνόματος', 'de nome'],
  ['ὀνόματι', 'em nome'],
  ['ὀνόματα', 'nomes'],
  ['ὀνομάτων', 'de nomes'],
  ['ὀνόμασι', 'em nomes'],
  ['ἐνώπιον', 'diante de'],
  ['ἐναντίον', 'diante de'],
  ['οὐρανός', 'céu'],
  ['οὐρανοῦ', 'do céu'],
  ['οὐρανῷ', 'no céu'],
  ['οὐρανόν', 'céu (ac)'],
  ['οὐρανοί', 'céus'],
  ['οὐρανῶν', 'dos céus'],
  ['οὐρανοῖς', 'nos céus'],
  ['οὐρανούς', 'céus (ac)'],
  ['οὔτε', 'nem'],
  ['ἡμέρα', 'dia'],
  ['ἡμέρας', 'de dia'],
  ['ἡμέρᾳ', 'em dia'],
  ['ἡμέραν', 'dia (ac)'],
  ['ἡμέραι', 'dias'],
  ['ἡμερῶν', 'de dias'],
  ['ἡμέραις', 'em dias'],
  ['ὅπου', 'onde'],
  ['μᾶλλον', 'antes/ao invés'],

  // ─── ADJETIVOS COMUNS ─────────────────────────────────────
  ['μέγας', 'grande'],
  ['μεγάλη', 'grande'],
  ['μέγα', 'grande'],
  ['μεγάλου', 'de grande'],
  ['μεγάλῳ', 'a grande'],
  ['μεγάλην', 'grande (ac)'],
  ['μικρός', 'pequeno'],
  ['μικρόν', 'pequeno'],
  ['μικροί', 'pequenos'],
  ['πολύς', 'muito'],
  ['πολλή', 'muita'],
  ['πολύ', 'muito'],
  ['πολλοί', 'muitos'],
  ['πολλούς', 'muitos (ac)'],
  ['πολλῶν', 'de muitos'],
  ['πολλοῖς', 'aos muitos'],
  ['πολλά', 'muitas'],
  ['πολλάκις', 'muitas vezes'],
  ['ὀλίγος', 'pouco'],
  ['ὀλίγοι', 'poucos'],
  ['πρῶτος', 'primeiro'],
  ['πρώτη', 'primeira'],
  ['πρῶτον', 'primeiro (ac)'],
  ['πρώτου', 'de primeiro'],
  ['πρώτῃ', 'em primeiro'],
  ['πρώτην', 'primeira (ac)'],
  ['πρῶτοι', 'primeiros'],
  ['ἔσχατος', 'último'],
  ['ἔσχατον', 'último (ac)'],
  ['ἔσχατοι', 'últimos'],
  ['ἄλλος', 'outro'],
  ['ἄλλη', 'outra'],
  ['ἄλλο', 'outro'],
  ['ἄλλον', 'outro (ac)'],
  ['ἄλλοι', 'outros'],
  ['ἄλλων', 'de outros'],
  ['ἄλλοις', 'aos outros'],
  ['ἄλλους', 'outros (ac)'],
  ['ἕτερος', 'outro (de dois)'],
  ['ἑτέρου', 'de outro'],
  ['ἑτέρῳ', 'a outro'],
  ['ἕτερον', 'outro (ac)'],
  ['ἑτέρων', 'de outros'],
  ['ἑτέρους', 'outros (ac)'],
  ['ἴδιος', 'próprio'],
  ['ἰδίᾳ', 'em particular'],
  ['ἴδιον', 'próprio (ac)'],
  ['ἰδίου', 'de próprio'],
  ['ἰδίοις', 'aos próprios'],
  ['ἴδιοι', 'próprios'],
  ['καινός', 'novo'],
  ['καινή', 'nova'],
  ['καινόν', 'novo (ac)'],
  ['παλαιός', 'velho'],
  ['παλαιά', 'velha'],
  ['ζῶν', 'vivente'],
  ['ζῶσα', 'vivente (fem)'],
  ['ζῶντα', 'vivente (ac)'],
  ['ζῶντας', 'viventes (ac)'],
  ['ζώντων', 'de viventes'],
  ['νεκρός', 'morto'],
  ['νεκροί', 'mortos'],
  ['νεκρῶν', 'de mortos'],
  ['νεκρόν', 'morto (ac)'],

  // ─── NÚMEROS ──────────────────────────────────────────────
  ['εἷς', 'um'],
  ['μία', 'uma'],
  ['ἕν', 'um (neut)'],
  ['ἑνός', 'de um'],
  ['μιᾶς', 'de uma'],
  ['δύο', 'dois'],
  ['τρεῖς', 'três'],
  ['τρία', 'três (neut)'],
  ['τέσσαρες', 'quatro'],
  ['τέσσαρα', 'quatro (neut)'],
  ['πέντε', 'cinco'],
  ['ἕξ', 'seis'],
  ['ἑπτά', 'sete'],
  ['ὀκτώ', 'oito'],
  ['ἐννέα', 'nove'],
  ['δέκα', 'dez'],
  ['δώδεκα', 'doze'],
  ['πεντήκοντα', 'cinquenta'],
  ['ἑκατόν', 'cem'],
  ['χίλιοι', 'mil'],
  ['χίλια', 'mil (neut)'],

  // ─── ADVÉRBIOS COMUNS ─────────────────────────────────────
  ['νῦν', 'agora'],
  ['τότε', 'então'],
  ['εὐθέως', 'imediatamente'],
  ['εὐθύς', 'imediatamente'],
  ['πάλιν', 'de novo'],
  ['ἔτι', 'ainda'],
  ['οὐκέτι', 'não mais'],
  ['μηκέτι', 'não mais'],
  ['ἤδη', 'já'],
  ['σήμερον', 'hoje'],
  ['αὔριον', 'amanhã'],
  ['χθές', 'ontem'],
  ['ἀεί', 'sempre'],
  ['ἀπάρτι', 'de agora em diante'],
  ['ὧδε', 'aqui'],
  ['ἐκεῖ', 'ali'],
  ['ποῦ', 'onde?'],
  ['ποῖ', 'para onde?'],
  ['πῶς', 'como?'],
  ['τί', 'que/o quê?'],
  ['τίς', 'quem?'],
  ['τίνος', 'de quem?'],
  ['τίνι', 'a quem?'],
  ['τίνα', 'quem (ac)?'],
];

// Constrói o dicionário final (última entrada vence em caso de duplicata).
export const MANUAL_GLOSSES: Record<string, string> = Object.fromEntries(GLOSS_LIST);

// Marcador de versão
export const GLOSSARY_VERSION = '0.3.0';
